# Ripple CBDC demo deployment

networks:
  trusted-contract-main:
  trusted-contract-mongo:
  trusted-contract-execution-enclave:

services:
  # Docs: https://github.com/nginx-proxy/nginx-proxy
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    networks:
      - trusted-contract-main
      - trusted-contract-mongo
      - trusted-contract-execution-enclave
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/tls:/etc/nginx/certs:ro

  trusted-contract-main-api:
    image: ghcr.io/ntls-io/sgx-wallet-hw:ripple-cbdc-challenge
    environment:
      VIRTUAL_HOST: trusted-contract-main-api.ntls.io
      BIND_ADDR: "0.0.0.0:8080"
      CERT_NAME: ntls-api
    networks:
      - trusted-contract-main
    volumes:
      - trusted-contract-store-main:/app/vault_store
    read_only: true
    init: true
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    expose:
      - "8080"

  trusted-contract-mongo-api:
    image: ghcr.io/ntls-io/trusted-contract-mongodb-api:main
    environment:
      VIRTUAL_HOST: trusted-contract-mongo-api.ntls.io
      VIRTUAL_PATH: /
      BIND_ADDR: "0.0.0.0:8000"
      CERT_NAME: ntls-api

      PRIMARY_ORIGIN: "https://trusted-contract-mongo-api.ntls.io"
      STAGING_MODE: 1
      WALLET_DB_CONNECTION_STRING: ${TRUSTED_CONTRACT_DB_CONNECTION_STRING}
      WALLET_DB_NAME: ${TRUSTED_CONTRACT_DB_NAME}
    networks:
      - trusted-contract-mongo
    init: true
    expose:
      - "8000"

  trusted-contract-execution-enclave:
    image: ghcr.io/ntls-io/trusted-contract-execution-enclave-hw:main
    environment:
      VIRTUAL_HOST: trusted-contract-execution-enclave.ntls.io
      BIND_ADDR: "0.0.0.0:8000"
      CERT_NAME: ntls-api
    networks:
      - trusted-contract-execution-enclave
    volumes:
      - trusted-contract-store-execution:/app/wallet_store
    read_only: false
    init: true
    devices:
      - /dev/sgx/enclave
      - /dev/sgx/provision
    expose:
      - "8000"

volumes:
  trusted-contract-store-main:
  trusted-contract-store-execution: